### ISSUE TITLE
update to gnome 47

### ISSUE THREAD

**Issue by Howarddj** [AlynxZhou/gnome-shell-extension-net-speed#10]
just needs metadata.json editing to recognise gnome shell 47.

everything still works as it should.

**Comment by AlynxZhou** [comment]
https://github.com/AlynxZhou/gnome-shell-extension-net-speed/commit/4f6d6fa9e3dfd3c0b5100a12f9ac494e39ba12b9

**Comment by khaled-0** [comment]
you forgot to push the update to extension store

**Comment by AlynxZhou** [comment]
> you forgot to push the update to extension store

I personally don't use extension.g.o and I have to manually pack extension and upload to the store so it might not be updated asap. You could try directly clone this repo.
