### ISSUE TITLE
Incompatible with Gnome 44.2

### ISSUE THREAD

**Issue by timhorn1** [AlynxZhou/gnome-shell-extension-net-speed#5]
This extension is great and I really want to use it in future. But it unfortunately got disabled from Gnome with the message: Incompatible with the current gnome version (44.2).
It would be great if the extension receives an update, so that it can be used in future.

**Comment by AlynxZhou** [comment]
> This extension is great and I really want to use it in future. But it unfortunately got disabled from Gnome with the message: Incompatible with the current gnome version (44.2). It would be great if the extension receives an update, so that it can be used in future.

I am using it on GNOME 44.2, you may check whether you need to update this extension.

**Comment by AlynxZhou** [comment]
I may forget to make a release. Will do soon.

**Comment by AlynxZhou** [comment]
Should be available now on <extensions.gnome.org>.

**Comment by timhorn1** [comment]
Thanks. Extension got updated automatically for me.
