### ISSUE TITLE
Network interface selection

### ISSUE THREAD

**Issue by ivanjx** [AlynxZhou/gnome-shell-extension-net-speed#6]
Is it possible to have a setting to monitor a specific interface instead of combining all of them? I use a vpn app and my network speed is not very accurate because it creates a new interface. Thanks.

**Comment by ivanjx** [comment]
Sorry it seems that it is my docker container that is causing the speed mismatch since i put a tunnel to my server there. Maybe excluding the network interfaces created by docker is enough for me. Here are some interfaces it creates:

- docker0
- veth1dd2116@if5
- veth7b4d9ca@if7

And here is what my vpn creates:

- utun420

**Comment by AlynxZhou** [comment]
Should be fixed by <https://github.com/AlynxZhou/gnome-shell-extension-net-speed/commit/a591214b0c1e2b23aa427cdcf57db35beb8e9d10>, check the git master.
