### ISSUE TITLE
 GNOME 45 support

### ISSUE THREAD

**Issue by craftergarage** [AlynxZhou/gnome-shell-extension-net-speed#7]
GNOME 45 is in beta now, Please add support for it to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

**Comment by AlynxZhou** [comment]
I will do this until I have GNOME 45 on my machine, or when someone would like to help me with a PR. Currently Arch Linux don't have GNOME 45 in its repo so I cannot do this, but I think soon we will have it.

**Comment by AlynxZhou** [comment]
Currently done in the git master, not doing release for AUR and e.g.o yet, if you need it, just clone the git version, or wait for release after I have dinner.
